---
- name: "Validate constraints of {{ module.group }} ({{ module.name }})"
  include_tasks: "{{ stackhead__roles }}/stackhead_module_api/tasks_internal/validate-module-constraints.yml"
- set_fact:
    loaded_config: "{{ ansible_facts[module.name | getstackhead.stackhead.module_vars_name] }}"
- name: "Load module variables"
  include_vars: "{{ var_path }}"
  when: lookup('pipe', '[ -f ' ~ var_path ~ ' ]; echo $?') == '0'
  with_items:
    - "{{ loaded_config.role_path }}/defaults/main.yml"
    - "{{ loaded_config.role_path }}/vars/main.yml"
  loop_control:
    loop_var: var_path
- block:
  - debug:
      msg: "{{ module }}"
  - include_tasks: "{{ stackhead__roles }}/stackhead_module_api/tasks_internal/run-migrations.yml"
  - name: "{{ stackhead_action }} {{ module.group }} ({{ module.name }}) configuration"
    include_tasks: "{{ include_file_path }}"
    when: lookup('pipe', '[ -f ' ~ include_file_path ~ ' ]; echo $?') == '0' or not module.optional|d(false)|bool
    vars:
      include_file_path: "{{ module_role_path }}/tasks/steps/{{ stackhead_action }}.yml"
  vars:
    module_role_path: "{{ lookup('getstackhead.stackhead.role_path', module.name) }}"
