# included by replace-provider.yml – should not be used alone.
#
# expects provider file to contain both old and new versions of the provider
# so we can savely replace the provider in state
# replace-provider.yml will later remove the old provider version
---
- include_tasks: "../roles/config_terraform/tasks/execute.yml"
  vars:
    terraform_folder: "{{ project_folder }}/terraform/"
- name: "Replace Terraform provider {{ provider_old }} -> {{ provider_new }}"
  shell:
    cmd: "terraform state replace-provider -auto-approve '{{ provider_old }}' '{{ provider_new }}'"
    chdir: "{{ project_folder }}"
