# included by replace-provider.yml – should not be used alone.
#
# expects provider file to contain both old and new versions of the provider
# so we can savely replace the provider in state
# replace-provider.yml will later remove the old provider version
---
- name: "Check if tfstate exists"
  stat:
    path: "{{ terraform_folder }}/terraform.tfstate"
  register: tfstate_exist
- include_tasks: "../roles/config_terraform/tasks/execute.yml"
  when: tfstate_exist.stat.exists
- name: "Replace Terraform provider {{ provider_old }} -> {{ provider_new }}"
  when: tfstate_exist.stat.exists
  shell:
    cmd: "terraform state replace-provider -auto-approve '{{ provider_old }}' '{{ provider_new }}'"
    chdir: "{{ terraform_folder }}"
