# Setup crontask for applying Terraform files every x minutes
#
# Input:
# - update_interval (default: update interval set in stackhead_config
#
- shell: which terraform
  register: terraform_bin_abs_path
- name: Create StackHead Terraform apply service
  include_role:
    name: openstack_systemd_service
  vars:
    systemd_services:
      - service_name: "stackhead-apply-terraform-{{ project_name }}"
        service_type: oneshot
        working_directory: "{{ stackhead__tf_project_folder }}"
        environment:
          TF_DATA_DIR: "{{ stackhead__tf_data_dir }}"
          TF_IN_AUTOMATION: 1
        execstarts:
          - "{{ terraform_bin_abs_path.stdout }} apply -auto-approve -input=false"
        timer:
          state: "started"
          options:
            Unit: "stackhead-apply-terraform-{{ project_name }}.service"
            OnCalendar: "{{ update_interval|d(stackhead_config.terraform.update_interval) }}"
            Persistent: true
