package ansible

import (
	"io/ioutil"
	"os"
	"path/filepath"
	"text/template"
)

type InventoryOptions struct {
	IpAddress string
}

func IpAddress(text string) InventoryOption {
	return func(args *InventoryOptions) {
		args.IpAddress = text
	}
}

type InventoryOption func(*InventoryOptions)

func CreateInventoryFile(options ...InventoryOption) (string, error) {
	opts := &InventoryOptions{}
	for _, setter := range options {
		setter(opts)
	}

	tmpFile, err := ioutil.TempFile("", "inventory")
	if err != nil {
		return "", err
	}

	filePath, err := filepath.Abs(tmpFile.Name())
	if err != nil {
		os.Remove(tmpFile.Name())
		return "", err
	}

	t, err := template.New("ansible_inventory").Parse(`# This file was generated by StackHead.
---
all:
  vars:
    ansible_user: root
    ansible_connection: ssh
  hosts:
    mackerel:
      ansible_host: {{ .IpAddress }}
`)

	if err = t.Execute(tmpFile, opts); err != nil {
		return "", err
	}

	// Close the file
	if err := tmpFile.Close(); err != nil {
		return "", err
	}

	return filePath, nil
}
